### ISSUE TITLE
Library name

### ISSUE THREAD

**Issue by Ghyro** [Lotus19955/Lessons#1]
Rename the Library main class with clear name
![image](https://user-images.githubusercontent.com/35216513/111902370-78d81f80-8a3d-11eb-8a92-b98a97dc5dbe.png)

**Comment by Lotus19955** [comment]
fixed

**Comment by Ghyro** [comment]
@Lotus19955 you have changed a class name (it's ok) but you must change file name as well
![image](https://user-images.githubusercontent.com/35216513/111907334-26a2f880-8a55-11eb-9b4e-f02a42a7e42b.png)
![image](https://user-images.githubusercontent.com/35216513/111907337-2d317000-8a55-11eb-9011-5a9cd38cff07.png)
