### ISSUE TITLE
Method name

### ISSUE THREAD

**Issue by Ghyro** [Lotus19955/Lessons#3]
Your function finds an element an existing array based on index, but not vice a versa
**Rename it please**
![image](https://user-images.githubusercontent.com/35216513/111902450-d2404e80-8a3d-11eb-8688-01a51824e6d2.png)

**Comment by Lotus19955** [comment]
fixed

**Comment by Ghyro** [comment]
@Lotus19955 what does it mean "Element" ? If I would like to use your library and I will create an array
I have got a code myArray.Element
What is Element?
Use clean naming like "FindElementByValue", etc.
![Uploading image.png…]()
