### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by Ghyro** [Lotus19955/Lessons#5]
Do code review and refactoring and try to set a clear name for objects
Remove unused comments
![image](https://user-images.githubusercontent.com/35216513/111902566-63afc080-8a3e-11eb-8fa4-6dbdb102244e.png)

**Comment by Lotus19955** [comment]
fixed

**Comment by Ghyro** [comment]
@Lotus19955 there is a new space, fix it
![image](https://user-images.githubusercontent.com/35216513/111907219-a2e90c00-8a54-11eb-865b-203f1c62f2f2.png)
